// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.28.3
// source: hoge.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetHogeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHogeRequest) Reset() {
	*x = GetHogeRequest{}
	mi := &file_hoge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHogeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHogeRequest) ProtoMessage() {}

func (x *GetHogeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hoge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHogeRequest.ProtoReflect.Descriptor instead.
func (*GetHogeRequest) Descriptor() ([]byte, []int) {
	return file_hoge_proto_rawDescGZIP(), []int{0}
}

func (x *GetHogeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetHogeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hoge          *Hoge                  `protobuf:"bytes,1,opt,name=hoge,proto3" json:"hoge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHogeResponse) Reset() {
	*x = GetHogeResponse{}
	mi := &file_hoge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHogeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHogeResponse) ProtoMessage() {}

func (x *GetHogeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hoge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHogeResponse.ProtoReflect.Descriptor instead.
func (*GetHogeResponse) Descriptor() ([]byte, []int) {
	return file_hoge_proto_rawDescGZIP(), []int{1}
}

func (x *GetHogeResponse) GetHoge() *Hoge {
	if x != nil {
		return x.Hoge
	}
	return nil
}

type Hoge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hoge) Reset() {
	*x = Hoge{}
	mi := &file_hoge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hoge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hoge) ProtoMessage() {}

func (x *Hoge) ProtoReflect() protoreflect.Message {
	mi := &file_hoge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hoge.ProtoReflect.Descriptor instead.
func (*Hoge) Descriptor() ([]byte, []int) {
	return file_hoge_proto_rawDescGZIP(), []int{2}
}

func (x *Hoge) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Hoge) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hoge) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_hoge_proto protoreflect.FileDescriptor

var file_hoge_proto_rawDesc = string([]byte{
	0x0a, 0x0a, 0x68, 0x6f, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x68, 0x6f,
	0x67, 0x65, 0x22, 0x20, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x31, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x67, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x68, 0x6f, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x68, 0x6f, 0x67, 0x65, 0x2e, 0x48, 0x6f, 0x67,
	0x65, 0x52, 0x04, 0x68, 0x6f, 0x67, 0x65, 0x22, 0x4c, 0x0a, 0x04, 0x48, 0x6f, 0x67, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x45, 0x0a, 0x0b, 0x48, 0x6f, 0x67, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x67, 0x65, 0x12,
	0x14, 0x2e, 0x68, 0x6f, 0x67, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x68, 0x6f, 0x67, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x48, 0x6f, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2b, 0x5a, 0x29,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x72, 0x69, 0x6d, 0x75,
	0x72, 0x61, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x2f, 0x64, 0x65,
	0x6d, 0x6f, 0x32, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var (
	file_hoge_proto_rawDescOnce sync.Once
	file_hoge_proto_rawDescData []byte
)

func file_hoge_proto_rawDescGZIP() []byte {
	file_hoge_proto_rawDescOnce.Do(func() {
		file_hoge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hoge_proto_rawDesc), len(file_hoge_proto_rawDesc)))
	})
	return file_hoge_proto_rawDescData
}

var file_hoge_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_hoge_proto_goTypes = []any{
	(*GetHogeRequest)(nil),  // 0: hoge.GetHogeRequest
	(*GetHogeResponse)(nil), // 1: hoge.GetHogeResponse
	(*Hoge)(nil),            // 2: hoge.Hoge
}
var file_hoge_proto_depIdxs = []int32{
	2, // 0: hoge.GetHogeResponse.hoge:type_name -> hoge.Hoge
	0, // 1: hoge.HogeService.GetHoge:input_type -> hoge.GetHogeRequest
	1, // 2: hoge.HogeService.GetHoge:output_type -> hoge.GetHogeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hoge_proto_init() }
func file_hoge_proto_init() {
	if File_hoge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hoge_proto_rawDesc), len(file_hoge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hoge_proto_goTypes,
		DependencyIndexes: file_hoge_proto_depIdxs,
		MessageInfos:      file_hoge_proto_msgTypes,
	}.Build()
	File_hoge_proto = out.File
	file_hoge_proto_goTypes = nil
	file_hoge_proto_depIdxs = nil
}
